services:
  - type: web
    name: message-encryption
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    port: 8080
    healthCheckPath: /
    domains:
      - message-encryption.onrender.com
    envVars:
      - key: PORT
        value: "8080"
    plan: free
